/*
 * Localization Root strings
 */

define( function() {
	return {
		root: {
			'ag': 'Average grade',
			'ar': 'Archive',
			'bftc': 'You have banned from this course',
			'course': 'Course' ,
			'cation': 'Courses added',
			'cetion': 'Courses ended',
			'cdate': 'Creation Date',
			'cd': 'Cheat detected',
			'ce': 'Compile Error',
			'cht': 'Cheat',
			'crpp': 'Count of records per page',
			'cscnm': 'You cannot send your codes, because you are not a member yet',
			'date' : 'Date',
			'deadline': 'Deadline',
			'eftiv': 'Effective',
			'eg': 'Exercise Grade',
			'engy': 'Exercises were not graded yet',
			'expired': 'Expired',
			'fce': 'Find this course exercises',
			'frd': 'File received date',
			'ftc': 'For test case',
			'graded': 'Graded',
			'gdate': 'Grading Date',
			'll': 'lastLogin',
			'mg': 'Max grade',
			'name' : 'Name',
			'n': 'No',
			'ng': 'Not graded',
			'nr': 'Not received',
			'number' : 'Number',
			'nxt': 'Next',
			'nzar': 'No Zip archive received',
			'open': 'Open',
			'o': 'Other',
			'optionalset': 'Optional problemset',
			'pl': 'Programming Language',
			'pgtion': 'Problemset grading',
			'pation': 'New problemsets',
			'problemset' : 'Problemset',
			'prv': 'Previous',
			'psc': 'Number of Problemsets',
			're': 'Runtime Error',
			'rgs': 'Register',
			'rt': 'Running Time',
			'pw.': 'Please wait...',
			'sc': 'Source code',
			'setnum': 'Set number',
			'sgin': 'Login',
			'sgot': 'Logout',
			'snd': 'Send',
			'stc': 'Number of Students',
			'svt': 'Server Time',
			'sza': 'Select your zipped archive',
			'rshp': 'Do you want send them again? Ok, select your zipped archive',
			'tchr' : 'Teacher',
			'tci': 'Test case input',
			'tcco': 'Test case correct output',
			'tco': 'Test case output',
			'tsg': 'Total set grade',
			'y': 'Yes',
			'yasc': 'You already sent your codes',
			'ynm': 'You are not member yet',
			'yshps': 'You can send your homework in Problemset section',
			'wage' : 'Wage',
			'zfc': 'Zip file was corrupted'
		},

		'fa': true
	};
});
